### ISSUE TITLE
Add ability to define build systems via manifest files

### ISSUE THREAD

**Issue by ChrisTimperley** [squaresLab/BugZoo#167]
It should be possible for users to use the manifest file format to define new build systems for their snapshots.

### Example manifest file definition

```yaml
build-systems:
  - name: waf
    commands:
        prebuild: "./waf configure [:opts:]"
        build: "./waf build -j [:threads=1:]"
        clean: "./waf clean"
        coverage: >
          ./waf configure LDFLAGS='--coverage' CXXFLAGS='--coverage' CFLAGS='--coverage'

  - name: custom
    commands:
      prebuild: "[:prebuild:]"
      build: "[:build:]"
      clean: "[:clean:]"
      coverage: "[:coverage:]"

snapshots:
  - name: foo
    build-system: waf

  - name: bar
    build-system:
      type: waf
      options:
        opts: --Wno-errors

  - name: i_would_like_a_custom_bug
    build-system:
      type: custom
      options:
        prebuild: exit 0
```

### Data structure sketch

```
class BuildSystem:
  name: str
  commands: Dict[str, str]
```

### Example server-side API usage

```
bz.containers.build(container, "build", threads=1)
```

## Development Roadmap

To reduce interference with the existing codebase, we should implement this functionality over several steps:

1. refactor Compiler class:
    * rename to BuildSystem
    * refactor compiler to contain strings for each of its commands.
    * add name property to compilers
2. implement server-side API that accepts options but ignores them.
